# Generated by Django 4.2.24 on 2025-09-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
