# Generated by Django 4.2.24 on 2025-09-13 12:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Titre du CV')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('template', models.CharField(choices=[('modern', 'Moderne'), ('classic', 'Classique'), ('creative', 'Créatif'), ('minimal', 'Minimaliste')], default='modern', max_length=20, verbose_name='Template')),
                ('color_scheme', models.CharField(default='blue', max_length=50, verbose_name='Schéma de couleurs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='Dernière consultation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='intermediate', max_length=20, verbose_name='Niveau')),
                ('percentage', models.PositiveIntegerField(default=50, help_text='Pourcentage de maîtrise (0-100)', verbose_name='Pourcentage')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(verbose_name='Description')),
                ('technologies', models.CharField(blank=True, help_text='Séparez les technologies par des virgules', max_length=500, null=True, verbose_name='Technologies utilisées')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Lien du projet')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-start_date', '-order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Portfolio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='cv_photos/', verbose_name='Photo de profil')),
                ('objective', models.TextField(blank=True, null=True, verbose_name='Objectif professionnel')),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Informations personnelles',
                'verbose_name_plural': 'Informations personnelles',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Langue')),
                ('level', models.CharField(choices=[('basic', 'Notions de base'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('native', 'Langue maternelle'), ('fluent', 'Courant')], max_length=20, verbose_name='Niveau')),
                ('certification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Certification')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Poste')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('description', models.TextField(verbose_name='Description')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Réalisations')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date', '-order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='Diplôme')),
                ('institution', models.CharField(max_length=200, verbose_name='Établissement')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True, verbose_name="Domaine d'études")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Formation en cours')),
                ('gpa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Moyenne')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Réalisations')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_date', '-order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la certification')),
                ('issuer', models.CharField(max_length=200, verbose_name='Organisme émetteur')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de la certification')),
                ('issue_date', models.DateField(verbose_name="Date d'obtention")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='Lien de vérification')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date', '-order'],
            },
        ),
    ]
