# Generated by Django 4.2.24 on 2025-09-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Lien GitHub'),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn'),
        ),
    ]
