# Generated by Django 4.2.24 on 2025-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_github_cv_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio'),
        ),
    ]
