# Generated by Django 4.2.24 on 2025-09-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cv_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='portfolio',
        ),
    ]
